#' @param run_date the model run_date
#'
#' Run the prior model
#'
#' @description
#' The prior model is a modification of Dr. Alan Abramovitz's *Time for Change*
#' model that generates state-level estimates of the two-party incumbent
#' voteshare at the national level based three variables: real annualized gdp
#' growth in the 2nd quarter of the election year, presidential net approval on
#' election day, and whether or not the incumbent is running for re-election.
#'
#' The state-level estimates are simply an offset from the national results
#' given the estimated partisan lean generated by the pvi model.
#'
#' The prior model is dependent on the results of the approval model, which is
#' updated daily. Therefore, the prior model must also update daily and thus is
#' not dependent on "trigger files." Minor changes to the following files,
#' however, warrant a note and version update. Major methodological changes may
#' warrant an explicit callout in the UI or a full rerun for all days since
#' 5/1/24.
#'
#' * data/static/abramovitz.csv
#' * out/approval-prior/e_day_approval_historical.csv
#' * out/approval/e_day_approval_current.csv
#' * out/pvi/pvi_summary.csv
#' * stan/priors.stan
#'
#' @param run_date the model run date
run_prior_model <- function(run_date) {

  # evaluate processing time
  start_ts <- Sys.time()

  # internal variable renaming
  int_run_date <- run_date

  # import economic data
  gdp <- fetch_gdp()
  cpi <- fetch_cpi()

  # estimate inflation relative to most recent cpi release
  max_cpi <-
    cpi %>%
    filter(DATE == max(DATE)) %>%
    pull(CPIAUCSL)

  cpi <-
    cpi %>%
    rename_with(str_to_lower) %>%
    rename(cpi = cpiaucsl) %>%
    mutate(inflation = max_cpi/cpi)

  # adjust gdp for inflation
  real_gdp <-
    gdp %>%
    rename_with(str_to_lower) %>%
    left_join(cpi) %>%
    select(-cpi) %>%
    mutate(real_gdp = gdp * inflation) %>%
    select(date, real_gdp)

  # append national data with 2nd quarter real annualized gdp growth
  prior_model_data <-
    read_csv("data/static/abramovitz.csv") %>%
    mutate(begin_quarter = mdy(paste0("4/1/", year - 1)),
           end_quarter = mdy(paste0("4/1/", year))) %>%
    left_join(real_gdp, by = c("begin_quarter" = "date")) %>%
    rename(begin_gdp = real_gdp) %>%
    left_join(real_gdp, by = c("end_quarter" = "date")) %>%
    rename(end_gdp = real_gdp) %>%
    mutate(real_gdp_growth = end_gdp/begin_gdp - 1) %>%
    select(-ends_with("quarter"),
           -ends_with("gdp"))

  # import historical election day approval estimates
  e_day_approval_historical <-
    read_csv("out/approval-prior/e_day_approval_historical.csv")

  # prep for passing to stan
  prior_model_data <-
    prior_model_data %>%
    left_join(e_day_approval_historical) %>%
    transmute(V = if_else(inc_party == "dem", dem, rep),
              V = V/(dem + rep),
              G = real_gdp_growth,
              I = inc_running,
              A_mu,
              A_sigma)

  # import current approval forecast
  e_day_approval_current <-
    read_csv("out/approval/e_day_approval_current.csv") %>%
    filter(run_date == int_run_date)

  # get most recent gdp growth
  G_new <-
    real_gdp %>%
    filter(date == max(date)) %>%
    mutate(begin_quarter = date - years(1)) %>%
    rename(end_quarter = date,
           end_gdp = real_gdp) %>%
    left_join(real_gdp, by = c("begin_quarter" = "date")) %>%
    rename(begin_gdp = real_gdp) %>%
    mutate(G_new = end_gdp/begin_gdp - 1) %>%
    pull(G_new)

  # import pvi prior
  pvi_summary <-
    read_csv("out/pvi/pvi_summary.csv")

  # compile model to exe
  prior_model <-
    cmdstan_model(
      "stan/priors.stan",
      dir = "exe/"
    )

  # pass to stan
  stan_data <-
    list(
      N = nrow(prior_model_data),
      V = prior_model_data$V,
      G = prior_model_data$G,
      I = prior_model_data$I,
      A_mu = prior_model_data$A_mu,
      A_sigma = prior_model_data$A_sigma,
      alpha_mu = 0,
      alpha_sigma = 1,
      beta_a_mu = 0,
      beta_a_sigma = 1,
      beta_g_mu = 0,
      beta_g_sigma = 1,
      beta_i_mu = 0,
      beta_i_sigma = 1,
      sigma_sigma = 1,
      A_new_mu = e_day_approval_current$mean,
      A_new_sigma = e_day_approval_current$sd,
      G_new = G_new,
      I_new = 1,
      S = nrow(pvi_summary),
      e_day_mu = pvi_summary$pvi_mu,
      e_day_sigma = pvi_summary$pvi_sd
    )

  # fit !
  prior_fit <-
    prior_model$sample(
      data = stan_data,
      seed = 2024,
      iter_warmup = 1000,
      iter_sampling = 1000,
      chains = 4,
      parallel_chains = 4
    )

  # extract state priors on the logit scale
  priors <-
    prior_fit$draws("theta_state", format = "df") %>%
    as_tibble() %>%
    pivot_longer(starts_with("theta_state"),
                 names_to = "parameter",
                 values_to = "estimate") %>%
    mutate(estimate = logit(estimate)) %>%
    drop_na() %>%
    group_by(parameter) %>%
    summarise(e_day_mu = mean(estimate),
              e_day_sigma = sd(estimate)) %>%
    ungroup() %>%
    mutate(parameter = parse_number(parameter)) %>%
    arrange(parameter) %>%
    bind_cols(pvi_summary) %>%
    select(state,
           e_day_mu,
           e_day_sigma)

  # write results to log
  priors %>%
    append_daily_estimate(
      "out/priors/priors.csv",
      run_date
    )

  # write results to log
  e_day_approval_current %>%
    append_daily_estimate(
      "out/approval/e_day_approval_current.csv",
      run_date
    )

  # diagnostics
  diagnostics <-
    prior_fit %>%
    diagnostic_summary()

  # evaluate processing time
  end_ts <- Sys.time()

  # generate model log
  model_log <-
    tibble(
      model_name = "priors",
      model_version = file.info("stan/priors.stan")$mtime,
      start_ts = start_ts,
      end_ts = end_ts,
      observations = stan_data$N,
      num_divergent = diagnostics$num_divergent,
      num_max_treedepth = diagnostics$num_max_treedepth,
      run_date = run_date
    )

  # write logs
  model_log %>% append_logs()

}

#' Import the most recent CPI data from FRED
#'
#' @description
#' Imports the most recent CPI data from the Federal Reserve Economic Data
#' (FRED) website. CPI is recorded monthly in nominal dollars.
fetch_cpi <- function() {

  current_date <- Sys.Date()
  last_month <- floor_date(floor_date(current_date, "month") - 1, "month")

  out <-
    read_csv(
      paste0(
        "https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23e1e9f0&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=1317&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=CPIAUCSL&scale=left&cosd=1947-01-01&coed=",
        last_month,
        "&line_color=%234572a7&link_values=false&line_style=solid&mark_type=none&mw=3&lw=2&ost=-99999&oet=99999&mma=0&fml=a&fq=Monthly&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=",
        current_date,
        "&revision_date=",
        current_date,
        "&nd=1947-01-01"
      )
    )

  return(out)

}

#' Import the most recent GDP data from FRED
#'
#' @description
#' Imports the most recent GDP data from the Federal Reserve Economic Data
#' (FRED) website. GDP is recorded quarterly in nominal dollars.
fetch_gdp <- function() {

  current_date <- Sys.Date()
  last_quarter <- floor_date(floor_date(current_date, "quarter") - 1, "quarter")

  out <-
    read_csv(
      paste0(
        "https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23e1e9f0&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=1317&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=GDP&scale=left&cosd=1947-01-01&coed=",
        last_quarter,
        "&line_color=%234572a7&link_values=false&line_style=solid&mark_type=none&mw=3&lw=2&ost=-99999&oet=99999&mma=0&fml=a&fq=Quarterly&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=",
        current_date,
        "&revision_date=",
        current_date,
        "&nd=1947-01-01"
      )
    )

  return(out)

}



